experiment_name: qft_inverse_qmio
experiment_type: qft_inverse
backend: qmio
output_db: output/db/timing_results.sqlite

sweep:
  n_qubits: [2, 4, 6, 8, 10]

controls:
  n_circuits: 1
  shots: 1000
  circuit_family: qft_inverse

repetitions: 3
randomize_order: true

backend_options:
  # If null, the latest file in calibration_dir is used automatically.
  calibration_file: null
  calibration_dir: /opt/cesga/qmio/hpc/calibrations